services:
  - type: web
    name: quicktrade
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn QuickTradePortal.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: quicktrade-db
          property: connectionString

databases:
  - name: quicktrade-db
    databaseName: quicktrade
    user: quicktrade
    plan: free 