services:
  - type: web
    name: quicktrade-web
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn QuickTradePortal.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: QuickTradePortal.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: WEB_CONCURRENCY
        value: 4
      - key: BASE_URL
        value: https://quicktrade-9zj5.onrender.com
